"""The reproducible result tables (Phase 9): what `spendguard report detection` writes."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from spendguard.detectors import owns
from spendguard.eval.injection import InjectionResult
from spendguard.eval.report import Spread, clean_data_check, detection_report
from spendguard.pipeline.ingest import IngestResult


def test_spread_is_the_mean_and_sample_standard_deviation() -> None:
    s = Spread.of([0.90, 0.95, 1.00])
    assert s.mean == pytest.approx(0.95)
    assert s.sd == pytest.approx(0.05)  # n - 1, not n
    assert Spread.of([0.5]).sd == 0.0
    assert Spread.of([0.9491, 0.95]).text() == "0.950 ± 0.001"


@pytest.mark.parametrize(
    ("detector", "anomaly_type", "shown"),
    [
        ("d1", "duplicate", True),
        ("d1", "split", False),  # the 0.000 the dashboard once misread
        ("d1", "all", False),  # a single-type detector has no pooled row
        ("baseline", "split", True),
        ("baseline", "all", True),
        ("someone_elses", "split", True),  # unknown: shown, never silently hidden
    ],
)
def test_a_detector_is_reported_only_for_what_it_detects(
    detector: str, anomaly_type: str, shown: bool
) -> None:
    assert owns(detector, anomaly_type) is shown


def test_the_clean_check_refuses_data_with_planted_anomalies(injected: InjectionResult) -> None:
    with pytest.raises(ValueError, match="planted"):
        clean_data_check(injected.out_db)


def test_the_detection_report_is_complete_and_traceable(
    tmp_path: Path, ingested: IngestResult, injected: InjectionResult
) -> None:
    report = detection_report(
        [injected.seed],
        injected={injected.seed: injected.out_db},
        clean_db=ingested.db_path,
        out_dir=tmp_path / "results",
        eval_dir=tmp_path / "eval",
    )

    assert report.reproduced and report.reproduced_cases > 0  # convention 4, checked every time
    assert set(report.clean.cases) == {"d1", "d2", "d3", "d4"}
    assert report.clean.transactions == ingested.rows_loaded

    case_rows = {(r.anomaly_type, r.detector) for r in report.rows if r.granularity == "case"}
    assert ("duplicate", "d1") in case_rows and ("duplicate", "baseline") in case_rows
    assert ("split", "d1") not in case_rows
    assert all(r.pr_auc is None for r in report.rows if r.granularity == "row")

    md_path, json_path = report.paths
    md = md_path.read_text(encoding="utf-8")
    assert "Generated by `spendguard report detection`" in md
    assert "do not edit by hand" in md
    assert f"Commit `{report.manifest['commit']}`" in md
    assert "| duplicate | **D1** |" in md
    assert "## Clean data" in md and "## Reproducibility" in md
    assert "`split_score_threshold`" in md  # the settings that decide what is flagged

    payload = json.loads(json_path.read_text(encoding="utf-8"))
    assert payload["seeds"] == [injected.seed]
    assert payload["manifest"]["settings"]["approval_threshold"] == 250_000.0
    assert payload["reproduced"] is True
