/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases
         * @description The case queue (FR-5.5). "Dismissed by agent" stays reachable as a filter (FR-5.4).
         */
        get: operations["list_cases_api_v1_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Case Detail
         * @description Everything an auditor needs to decide one case (FR-5.6).
         */
        get: operations["case_detail_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Case Evidence
         * @description A case's rows, a page at a time - a vendor case can hold hundreds.
         */
        get: operations["case_evidence_api_v1_cases__case_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Status
         * @description The human decision (FR-5.2). The agent never calls this.
         */
        patch: operations["update_status_api_v1_cases__case_id__status_patch"];
        trace?: never;
    };
    "/api/v1/demo/inject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject Demo
         * @description Plant anomalies in a bounded copy of the clean data, detect, report what was caught.
         */
        post: operations["inject_demo_api_v1_demo_inject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evaluation
         * @description Detector metrics against the baseline, agent metrics and ablations for one seed (FR-5.8).
         */
        get: operations["evaluation_api_v1_evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Can the stores be read? The LLM is reported as configured, never probed (see schema).
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Dashboard KPIs (FR-5.7). Flagged = investigated + queued, always.
         */
        get: operations["metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs
         * @description Run history, newest first, so the dashboard can say which run it shows.
         */
        get: operations["runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{row_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transaction
         * @description One row, for inspecting a citation. Read from the audit view: never the answer key.
         */
        get: operations["transaction_api_v1_transactions__row_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AblationRow */
        AblationRow: {
            /** Ablation Name */
            ablation_name: string;
            /** Citation Validity Deterministic */
            citation_validity_deterministic: number | null;
            /** Citation Validity Semantic */
            citation_validity_semantic: number | null;
            /** Configuration */
            configuration: string;
            /** Note Quality Score */
            note_quality_score: number | null;
            /** Triage Accuracy */
            triage_accuracy: number | null;
        };
        /**
         * AgentMetrics
         * @description Null where nothing has been measured yet - never a zero standing in for missing.
         */
        AgentMetrics: {
            /** Avg Latency Seconds */
            avg_latency_seconds: number | null;
            /** Avg Tokens */
            avg_tokens: number | null;
            /** Avg Tool Calls */
            avg_tool_calls: number | null;
            /** Citation Validity Deterministic */
            citation_validity_deterministic: number | null;
            /** Citation Validity Semantic */
            citation_validity_semantic: number | null;
            /** Notes */
            notes: number;
            /** Notes Failed After Retries */
            notes_failed_after_retries: number;
            /** Notes Regenerated */
            notes_regenerated: number;
            /** Triage Accuracy */
            triage_accuracy: number | null;
        };
        /** AnomalyBreakdown */
        AnomalyBreakdown: {
            /** Amount At Risk */
            amount_at_risk: string;
            /** Count */
            count: number;
        };
        /** AuditNote */
        AuditNote: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Citations Checked */
            citations_checked: number | null;
            /** Citations Passed */
            citations_passed: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deterministic Passed */
            deterministic_passed: number | null;
            /** Finding */
            finding: string;
            /** Model Name */
            model_name: string;
            /**
             * Note Id
             * Format: uuid
             */
            note_id: string;
            /** Policy Clauses */
            policy_clauses: string[];
            /** Recommended Action */
            recommended_action: string;
            /** Retry Count */
            retry_count: number;
            /** Semantic Passed */
            semantic_passed: number | null;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "likely_true_positive" | "likely_false_positive" | "inconclusive";
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "verified" | "unverified" | "failed_after_retries";
        };
        /** Case */
        Case: {
            /** Amount At Risk */
            amount_at_risk: string;
            /**
             * Anomaly Type
             * @enum {string}
             */
            anomaly_type: "duplicate" | "split" | "inflation" | "vendor_flag";
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detector */
            detector: string;
            /** Detector Score */
            detector_score: number;
            /** Dismissed By Agent */
            dismissed_by_agent: boolean;
            /** Investigated */
            investigated: boolean;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Reviewer Note */
            reviewer_note: string | null;
            /** Row Ids */
            row_ids: number[];
            /** Run Id */
            run_id: string;
            /**
             * Severity Band
             * @enum {string}
             */
            severity_band: "high" | "medium" | "low";
            /** Severity Final */
            severity_final: number | null;
            /** Severity Prelim */
            severity_prelim: number;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "under_review" | "confirmed" | "dismissed";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vendor Key */
            vendor_key: string | null;
        };
        /** CaseDetailResponse */
        CaseDetailResponse: {
            audit_note: components["schemas"]["AuditNote"] | null;
            case: components["schemas"]["Case"];
            /** Context Rows */
            context_rows: components["schemas"]["TransactionRow"][];
            /** Currency */
            currency: string;
            /** Evidence Rows */
            evidence_rows: components["schemas"]["TransactionRow"][];
            /** Evidence Total */
            evidence_total: number;
            /** Trace */
            trace: components["schemas"]["TraceStep"][];
        };
        /** CaseListResponse */
        CaseListResponse: {
            /** Currency */
            currency: string;
            /** Items */
            items: components["schemas"]["CaseSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * CaseSummary
         * @description A queue row: the case, plus enough of its note to triage from the list.
         */
        CaseSummary: {
            /** Amount At Risk */
            amount_at_risk: string;
            /**
             * Anomaly Type
             * @enum {string}
             */
            anomaly_type: "duplicate" | "split" | "inflation" | "vendor_flag";
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Citations Checked */
            citations_checked: number | null;
            /** Citations Passed */
            citations_passed: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detector */
            detector: string;
            /** Detector Score */
            detector_score: number;
            /** Dismissed By Agent */
            dismissed_by_agent: boolean;
            /** Finding Excerpt */
            finding_excerpt: string | null;
            /** Investigated */
            investigated: boolean;
            /** Reviewer Note */
            reviewer_note: string | null;
            /** Row Ids */
            row_ids: number[];
            /** Run Id */
            run_id: string;
            /**
             * Severity Band
             * @enum {string}
             */
            severity_band: "high" | "medium" | "low";
            /** Severity Final */
            severity_final: number | null;
            /** Severity Prelim */
            severity_prelim: number;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "under_review" | "confirmed" | "dismissed";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vendor Key */
            vendor_key: string | null;
            /** Verdict */
            verdict: ("likely_true_positive" | "likely_false_positive" | "inconclusive") | null;
            /** Verification Status */
            verification_status: ("verified" | "unverified" | "failed_after_retries") | null;
        };
        /** Citation */
        Citation: {
            /** Asserted */
            asserted: {
                [key: string]: unknown;
            };
            /**
             * Citation Id
             * Format: uuid
             */
            citation_id: string;
            /** Claim Index */
            claim_index: number;
            /** Claim Text */
            claim_text: string;
            /** Failure Reason */
            failure_reason: string | null;
            /** Row Exists */
            row_exists: boolean | null;
            /** Row Id */
            row_id: number;
            /** Supports Claim */
            supports_claim: boolean | null;
            /** Values Match */
            values_match: boolean | null;
        };
        /** DemoInjectRequest */
        DemoInjectRequest: {
            /**
             * Anomaly Count
             * @default 3
             */
            anomaly_count: number;
            /** Seed */
            seed?: number | null;
        };
        /** DemoInjectResponse */
        DemoInjectResponse: {
            /** Caught */
            caught: number;
            /** Dataset Rows */
            dataset_rows: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /** Other Cases */
            other_cases: number;
            /** Requested */
            requested: number;
            /** Results */
            results: components["schemas"]["DemoInjectResult"][];
            /** Seed */
            seed: number;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
        };
        /** DemoInjectResult */
        DemoInjectResult: {
            /** Amount At Risk */
            amount_at_risk: string;
            /**
             * Anomaly Type
             * @enum {string}
             */
            anomaly_type: "duplicate" | "split" | "inflation" | "vendor_flag";
            /** Case Id */
            case_id: string | null;
            /** Detected */
            detected: boolean;
            /** Detected By */
            detected_by: string | null;
            /** Detector Score */
            detector_score: number | null;
            /** Injected Row Ids */
            injected_row_ids: number[];
            /** Injection Group Id */
            injection_group_id: string;
        };
        /** DetectorMetrics */
        DetectorMetrics: {
            /** Anomaly Type */
            anomaly_type: string;
            /** Detector */
            detector: string;
            /** F1 */
            f1: number;
            /** Fn */
            fn: number;
            /** Fp */
            fp: number;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "case" | "row";
            /** Pr Auc */
            pr_auc: number | null;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** Tp */
            tp: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /** EvaluationResponse */
        EvaluationResponse: {
            /** Ablations */
            ablations: components["schemas"]["AblationRow"][];
            agent_metrics: components["schemas"]["AgentMetrics"];
            /** Baseline Metrics */
            baseline_metrics: components["schemas"]["DetectorMetrics"][];
            /** Dataset */
            dataset: string | null;
            /** Detector Metrics */
            detector_metrics: components["schemas"]["DetectorMetrics"][];
            /** Generated At */
            generated_at: string | null;
            /** Injected Anomaly Count */
            injected_anomaly_count: number | null;
            /** Run Id */
            run_id: string | null;
            /** Seed */
            seed: number;
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Rows */
            rows: components["schemas"]["TransactionRow"][];
            /** Total */
            total: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Case Store */
            case_store: boolean;
            /** Duckdb */
            duckdb: boolean;
            /** Llm Configured */
            llm_configured: boolean;
            /** Llm Model */
            llm_model: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** By Anomaly Type */
            by_anomaly_type: {
                [key: string]: components["schemas"]["AnomalyBreakdown"];
            };
            /** By Severity Band */
            by_severity_band: {
                [key: string]: number;
            };
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** By Verdict */
            by_verdict: {
                [key: string]: number;
            };
            /** By Verification Status */
            by_verification_status: {
                [key: string]: number;
            };
            /** Cases Flagged */
            cases_flagged: number;
            /** Cases Investigated */
            cases_investigated: number;
            /** Cases Queued */
            cases_queued: number;
            /** Converted From */
            converted_from: string | null;
            /** Currency */
            currency: string;
            /** Dataset */
            dataset: string | null;
            /** Evaluation Seed */
            evaluation_seed: number | null;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Run Id */
            last_run_id: string | null;
            /** Money At Risk */
            money_at_risk: string;
            /** Money At Risk Confirmed */
            money_at_risk_confirmed: string;
            /** Total Amount */
            total_amount: string;
            /** Total Transactions */
            total_transactions: number;
        };
        /** RunSummary */
        RunSummary: {
            /** Finished At */
            finished_at: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "ingest" | "detect" | "investigate" | "evaluate";
            /** Run Id */
            run_id: string;
            /** Seed */
            seed: number | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "failed";
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** StatusUpdateRequest */
        StatusUpdateRequest: {
            /** Reviewer Note */
            reviewer_note?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "under_review" | "confirmed" | "dismissed";
        };
        /** TraceStep */
        TraceStep: {
            /** Completion Tokens */
            completion_tokens: number | null;
            /** Detail */
            detail: string | null;
            /** Error */
            error: string | null;
            /** Kind */
            kind: string;
            /** Latency Ms */
            latency_ms: number;
            /** Prompt Tokens */
            prompt_tokens: number | null;
            /**
             * Role
             * @enum {string}
             */
            role: "investigator" | "verifier";
            /** Step Index */
            step_index: number;
            /** Tool Args */
            tool_args: {
                [key: string]: unknown;
            } | null;
            /** Tool Name */
            tool_name: string | null;
            /** Tool Result */
            tool_result: unknown;
        };
        /** TransactionRow */
        TransactionRow: {
            /** Amount */
            amount: string;
            /** Cited */
            cited: boolean;
            /** In Case */
            in_case: boolean;
            /** Invoice No */
            invoice_no: string | null;
            /** Item Category */
            item_category: string | null;
            /** Item Desc */
            item_desc: string | null;
            /** Officer Id */
            officer_id: string | null;
            /** Quantity */
            quantity: number | null;
            /** Row Id */
            row_id: number;
            /**
             * Txn Date
             * Format: date
             */
            txn_date: string;
            /** Unit Price */
            unit_price: string | null;
            /** Vendor Key */
            vendor_key: string;
            /** Vendor Name */
            vendor_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cases_api_v1_cases_get: {
        parameters: {
            query?: {
                status?: ("new" | "under_review" | "confirmed" | "dismissed")[] | null;
                anomaly_type?: ("duplicate" | "split" | "inflation" | "vendor_flag")[] | null;
                severity_band?: ("high" | "medium" | "low")[] | null;
                verdict?: ("likely_true_positive" | "likely_false_positive" | "inconclusive")[] | null;
                verification_status?: ("verified" | "unverified" | "failed_after_retries")[] | null;
                investigated?: boolean | null;
                dismissed_by_agent?: boolean | null;
                min_amount?: number | string | null;
                sort?: "severity_prelim" | "severity_final" | "amount_at_risk" | "created_at";
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseListResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    case_detail_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Unknown case */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    case_evidence_api_v1_cases__case_id__evidence_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceResponse"];
                };
            };
            /** @description Unknown case */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_status_api_v1_cases__case_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Unknown case */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    inject_demo_api_v1_demo_inject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoInjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoInjectResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A demo is already running, or no clean data to copy */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    evaluation_api_v1_evaluation_get: {
        parameters: {
            query?: {
                seed?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transaction_api_v1_transactions__row_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRow"];
                };
            };
            /** @description Unknown row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
